// react-sandbox/src/components/ConditionalRendering.tsx
import { useState } from 'react';

function ConditionalRendering() {

  const [shown, setShown] = useState(false);
  const show = () => setShown(!shown);

  return (
    <>
      {shown ? <div>Hello</div> : <h1>asdf</h1>}
      <br />
      <label htmlFor="show">
        <input id="show" type="checkbox" onChange={show} />
        Show me
      </label>
    </>
  );
}

export default ConditionalRendering;

// vue-sandbox/src/components/ConditionalRendering.vue
<template>
  <div v-if="shown">
    Hello
  </div>
  <div v-else>
    asdf
  </div>
  <br>
  <label for="show">
    <input v-model="shown" id="show" type="checkbox">
    Show me
  </label>
  <br>
  <button @click="show">Show me with callback</button>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const shown = ref(false);
const show = () => shown.value = !shown.value;
</script>
